<?php
/**
 * Copyright © Muon. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types=1);

namespace Muon\ApiSchemaExport\Model\Renderer;

use Magento\Framework\Phrase;
use Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface;
use Muon\ApiSchemaExport\Api\Data\OperationInterface;
use Muon\ApiSchemaExport\Api\Data\RenderContextInterface;
use Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer;

/**
 * Renders the surface as a JetBrains / VS Code HTTP client file.
 *
 * Emits a companion http-client.env.json carrying the baseUrl and an EMPTY token, so the file can
 * be committed and shared without ever having held a credential.
 */
class HttpRenderer extends AbstractRenderer
{
    /**
     * Renderer code.
     */
    public const CODE = 'http';

    /**
     * Magento serves its REST surface under this prefix.
     */
    private const REST_PREFIX = '/rest';

    /**
     * @param \Muon\ApiSchemaExport\Model\Renderer\ExampleBuilder $exampleBuilder
     * @param \Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer $serializer
     */
    public function __construct(
        private readonly ExampleBuilder $exampleBuilder,
        private readonly DocumentSerializer $serializer
    ) {
    }

    /**
     * @inheritDoc
     */
    public function getCode(): string
    {
        return self::CODE;
    }

    /**
     * @inheritDoc
     */
    public function getLabel(): Phrase
    {
        return __('HTTP client file (.http)');
    }

    /**
     * @inheritDoc
     */
    public function getFileExtension(RenderContextInterface $context): string
    {
        return 'http';
    }

    /**
     * @inheritDoc
     */
    public function getContentType(RenderContextInterface $context): string
    {
        return 'text/plain';
    }

    /**
     * @inheritDoc
     */
    public function render(ApiSurfaceInterface $surface, RenderContextInterface $context): string
    {
        $lines = [
            '# ' . $context->getTitle(),
            '#',
            '# Generated by Muon_ApiSchemaExport. Values in {{...}} come from http-client.env.json.',
            '# The bearer token ships EMPTY on purpose — fill it in locally, never commit it.',
            '# To scope a request to one store, insert the store code: {{baseUrl}}/rest/{storeCode}/V1/...',
            '',
        ];

        foreach ($this->groupByModule($surface) as $moduleName => $operations) {
            $lines[] = '';
            $lines[] = '# ===== ' . $moduleName . ' =====';
            foreach ($operations as $operation) {
                $lines[] = '';
                array_push($lines, ...$this->renderOperation($operation, $surface));
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @inheritDoc
     */
    public function getCompanionFiles(
        ApiSurfaceInterface $surface,
        RenderContextInterface $context
    ): array {
        return [
            'env.json' => $this->serializer->toJson([
                'dev' => [
                    self::VAR_BASE_URL => $context->getBaseUrl(),
                    // Deliberately empty. This file is meant to be shareable.
                    self::VAR_TOKEN => '',
                ],
            ]),
        ];
    }

    /**
     * Render one operation as a request block.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @param \Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface $surface
     * @return string[]
     */
    private function renderOperation(
        OperationInterface $operation,
        ApiSurfaceInterface $surface
    ): array {
        $path = $this->toPlaceholderPath($operation->getRoute(), '{{', '}}');

        $lines = [
            '### ' . $this->getSummary($operation),
            '# @name ' . $this->getOperationId($operation),
            '# ACL: ' . $this->getAclSummary($operation),
            '# Kind: ' . $operation->getKind(),
            sprintf(
                '%s {{%s}}%s%s',
                $operation->getHttpMethod(),
                self::VAR_BASE_URL,
                self::REST_PREFIX,
                $path
            ),
            'Authorization: Bearer {{' . self::VAR_TOKEN . '}}',
            'Content-Type: application/json',
            'Accept: application/json',
        ];

        if ($this->hasBody($operation)) {
            $lines[] = '';
            $lines[] = $this->renderBody($operation, $surface);
        }

        return $lines;
    }

    /**
     * Render an operation's request body.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @param \Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface $surface
     * @return string
     */
    private function renderBody(OperationInterface $operation, ApiSurfaceInterface $surface): string
    {
        $body = $this->exampleBuilder->forParameters(
            $this->getCallerParameters($operation),
            $surface->getTypes()
        );

        // A bulk endpoint takes an array of the single-item body.
        $payload = $this->isBodyArray($operation) ? [$body] : $body;

        return rtrim($this->serializer->toJson($payload));
    }
}
