<?php
/**
 * Copyright © Muon. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types=1);

namespace Muon\ApiSchemaExport\Model\Renderer;

use Magento\Framework\Phrase;
use Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface;
use Muon\ApiSchemaExport\Api\Data\OperationInterface;
use Muon\ApiSchemaExport\Api\Data\RenderContextInterface;
use Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer;

/**
 * Renders the surface as an OpenAPI 3.1 document.
 *
 * Security is declared as a bearer scheme only. No credential value appears anywhere in the
 * document.
 */
class OpenApiRenderer extends AbstractRenderer
{
    /**
     * Renderer code.
     */
    public const CODE = 'openapi';

    /**
     * Specification version emitted.
     */
    private const OPENAPI_VERSION = '3.1.0';

    /**
     * Reference root for component schemas.
     */
    private const REF_ROOT = '#/components/schemas/';

    /**
     * Magento serves its REST surface under this prefix.
     */
    private const REST_PREFIX = '/rest';

    /**
     * @param \Muon\ApiSchemaExport\Model\Renderer\SchemaBuilder $schemaBuilder
     * @param \Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer $serializer
     */
    public function __construct(
        private readonly SchemaBuilder $schemaBuilder,
        private readonly DocumentSerializer $serializer
    ) {
    }

    /**
     * @inheritDoc
     */
    public function getCode(): string
    {
        return self::CODE;
    }

    /**
     * @inheritDoc
     */
    public function getLabel(): Phrase
    {
        return __('OpenAPI 3.1 schema');
    }

    /**
     * @inheritDoc
     */
    public function getFileExtension(RenderContextInterface $context): string
    {
        return 'openapi.' . $this->serializer->getExtension($context);
    }

    /**
     * @inheritDoc
     */
    public function getContentType(RenderContextInterface $context): string
    {
        return $this->serializer->getContentType($context);
    }

    /**
     * @inheritDoc
     */
    public function render(ApiSurfaceInterface $surface, RenderContextInterface $context): string
    {
        $paths = [];
        foreach ($surface->getOperations() as $operation) {
            $path = self::REST_PREFIX . $this->toPlaceholderPath($operation->getRoute(), '{', '}');
            $paths[$path][strtolower($operation->getHttpMethod())] = $this->renderOperation($operation);
        }
        ksort($paths);

        $document = [
            'openapi' => self::OPENAPI_VERSION,
            'info' => [
                'title' => $context->getTitle(),
                'version' => '1.0.0',
                'description' => 'Generated by Muon_ApiSchemaExport for: '
                    . implode(', ', $surface->getModuleNames()),
            ],
            'servers' => [['url' => $context->getBaseUrl()]],
            'tags' => $this->renderTags($surface),
            'paths' => $this->schemaBuilder->asMap($paths),
            'components' => [
                'securitySchemes' => [
                    'bearerAuth' => ['type' => 'http', 'scheme' => 'bearer'],
                ],
                'schemas' => $this->schemaBuilder->asMap(
                    $this->schemaBuilder->forTypes($surface->getTypes(), self::REF_ROOT)
                ),
            ],
            'security' => [['bearerAuth' => []]],
        ];

        return $this->serializer->serialize($document, $context);
    }

    /**
     * Render the tag list, one per selected module.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface $surface
     * @return array<int,array<string,string>>
     */
    private function renderTags(ApiSurfaceInterface $surface): array
    {
        $tags = [];
        foreach (array_keys($this->groupByModule($surface)) as $moduleName) {
            $tags[] = ['name' => (string)$moduleName];
        }

        return $tags;
    }

    /**
     * Render one path-item operation.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<string,mixed>
     */
    private function renderOperation(OperationInterface $operation): array
    {
        $item = [
            'tags' => array_values($operation->getModuleNames()),
            'operationId' => $this->getOperationId($operation),
            'summary' => $this->getSummary($operation),
            'description' => $this->renderDescription($operation),
            'parameters' => $this->renderParameters($operation),
            'responses' => $this->renderResponses($operation),
        ];

        if ($this->hasBody($operation)) {
            $item['requestBody'] = [
                'required' => true,
                'content' => ['application/json' => ['schema' => $this->renderBodySchema($operation)]],
            ];
        }

        return $item;
    }

    /**
     * Render path and query parameters.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<int,array<string,mixed>>
     */
    private function renderParameters(OperationInterface $operation): array
    {
        $parameters = [];

        foreach ($this->getPathParameters($operation->getRoute()) as $name) {
            $declared = $operation->getInputParameters()[$name] ?? [];
            $parameters[] = [
                'name' => $name,
                'in' => 'path',
                'required' => true,
                'schema' => $this->schemaBuilder->forType(
                    isset($declared['type']) ? (string)$declared['type'] : 'string',
                    self::REF_ROOT
                ),
            ];
        }

        if ($operation->getHttpMethod() !== 'GET') {
            return $parameters;
        }

        foreach ($this->getCallerParameters($operation) as $name => $declared) {
            $parameters[] = [
                'name' => (string)$name,
                'in' => 'query',
                'required' => (bool)($declared['required'] ?? false),
                'schema' => $this->schemaBuilder->forType(
                    isset($declared['type']) ? (string)$declared['type'] : 'string',
                    self::REF_ROOT
                ),
            ];
        }

        return $parameters;
    }

    /**
     * Render the request-body schema, wrapping it in an array for bulk operations.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<string,mixed>
     */
    private function renderBodySchema(OperationInterface $operation): array
    {
        $schema = $this->schemaBuilder->forParameters(
            $this->getCallerParameters($operation),
            self::REF_ROOT
        );

        return $this->isBodyArray($operation)
            ? ['type' => 'array', 'items' => $schema]
            : $schema;
    }

    /**
     * Render the response map.
     *
     * Keys are HTTP status codes. PHP coerces numeric string keys to integers, so the returned
     * array is int-keyed; JSON encoding restores them as the object keys both specifications
     * require.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<array-key,mixed>
     */
    private function renderResponses(OperationInterface $operation): array
    {
        $output = $operation->getOutputParameters();
        $resultType = isset($output['result']['type']) ? (string)$output['result']['type'] : null;

        $success = ['description' => 'Success.'];
        if ($resultType !== null) {
            $success['content'] = [
                'application/json' => ['schema' => $this->schemaBuilder->forType($resultType, self::REF_ROOT)],
            ];
        }

        $responses = ['200' => $success, '400' => ['description' => 'Bad request.']];

        if ($operation->getAclResources() !== []) {
            $responses['401'] = ['description' => 'Unauthenticated.'];
            $responses['403'] = ['description' => 'Forbidden — the token lacks the required ACL resource.'];
        }
        if ($this->getPathParameters($operation->getRoute()) !== []) {
            $responses['404'] = ['description' => 'Not found.'];
        }

        return $responses;
    }

    /**
     * Build the long-form operation description.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return string
     */
    private function renderDescription(OperationInterface $operation): string
    {
        $parts = [
            trim($operation->getDescription()),
            '',
            'Declared by: ' . implode(', ', $operation->getModuleNames()),
            'Service: ' . $operation->getServiceClass() . '::' . $operation->getServiceMethod(),
            'ACL: ' . $this->getAclSummary($operation),
            'Kind: ' . $operation->getKind(),
        ];

        return trim(implode("\n", $parts));
    }
}
