<?php
/**
 * Copyright © Muon. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types=1);

namespace Muon\ApiSchemaExport\Model\Renderer;

use Magento\Framework\Phrase;
use Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface;
use Muon\ApiSchemaExport\Api\Data\OperationInterface;
use Muon\ApiSchemaExport\Api\Data\RenderContextInterface;
use Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer;

/**
 * Renders the surface as a Postman Collection v2.1 document.
 *
 * Modules become folders. Authentication is a collection-level bearer scheme reading a {{token}}
 * collection variable that is always emitted EMPTY, and a companion environment file carries the
 * same empty value, so an exported collection can be shared without leaking a credential.
 */
class PostmanRenderer extends AbstractRenderer
{
    /**
     * Renderer code.
     */
    public const CODE = 'postman';

    /**
     * Collection schema this document conforms to.
     */
    private const SCHEMA = 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json';

    /**
     * Magento serves its REST surface under this prefix.
     */
    private const REST_PREFIX = 'rest';

    /**
     * @param \Muon\ApiSchemaExport\Model\Renderer\ExampleBuilder $exampleBuilder
     * @param \Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer $serializer
     */
    public function __construct(
        private readonly ExampleBuilder $exampleBuilder,
        private readonly DocumentSerializer $serializer
    ) {
    }

    /**
     * @inheritDoc
     */
    public function getCode(): string
    {
        return self::CODE;
    }

    /**
     * @inheritDoc
     */
    public function getLabel(): Phrase
    {
        return __('Postman collection (v2.1)');
    }

    /**
     * @inheritDoc
     */
    public function getFileExtension(RenderContextInterface $context): string
    {
        return 'postman_collection.json';
    }

    /**
     * @inheritDoc
     */
    public function getContentType(RenderContextInterface $context): string
    {
        return 'application/json';
    }

    /**
     * @inheritDoc
     */
    public function render(ApiSurfaceInterface $surface, RenderContextInterface $context): string
    {
        $folders = [];
        foreach ($this->groupByModule($surface) as $moduleName => $operations) {
            $items = [];
            foreach ($operations as $operation) {
                $items[] = $this->renderItem($operation, $surface);
            }
            $folders[] = [
                'name' => $moduleName,
                'item' => $items,
            ];
        }

        return $this->serializer->toJson([
            'info' => [
                'name' => $context->getTitle(),
                'description' => 'Generated by Muon_ApiSchemaExport. The token variable is empty '
                    . 'by design — set it in your own environment, never in the collection.',
                'schema' => self::SCHEMA,
            ],
            'auth' => [
                'type' => 'bearer',
                'bearer' => [
                    ['key' => 'token', 'value' => '{{' . self::VAR_TOKEN . '}}', 'type' => 'string'],
                ],
            ],
            'variable' => [
                ['key' => self::VAR_BASE_URL, 'value' => $context->getBaseUrl(), 'type' => 'string'],
                ['key' => self::VAR_TOKEN, 'value' => '', 'type' => 'string'],
            ],
            'item' => $folders,
        ]);
    }

    /**
     * @inheritDoc
     */
    public function getCompanionFiles(
        ApiSurfaceInterface $surface,
        RenderContextInterface $context
    ): array {
        return [
            'postman_environment.json' => $this->serializer->toJson([
                'name' => $context->getTitle() . ' environment',
                'values' => [
                    [
                        'key' => self::VAR_BASE_URL,
                        'value' => $context->getBaseUrl(),
                        'type' => 'default',
                        'enabled' => true,
                    ],
                    [
                        // Deliberately empty. This file is meant to be shareable.
                        'key' => self::VAR_TOKEN,
                        'value' => '',
                        'type' => 'secret',
                        'enabled' => true,
                    ],
                ],
                '_postman_variable_scope' => 'environment',
            ]),
        ];
    }

    /**
     * Render one operation as a collection item.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @param \Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface $surface
     * @return array<string,mixed>
     */
    private function renderItem(OperationInterface $operation, ApiSurfaceInterface $surface): array
    {
        $request = [
            'method' => $operation->getHttpMethod(),
            'header' => [
                ['key' => 'Content-Type', 'value' => 'application/json'],
                ['key' => 'Accept', 'value' => 'application/json'],
            ],
            'url' => $this->renderUrl($operation),
            'description' => $this->renderDescription($operation),
        ];

        if ($this->hasBody($operation)) {
            $body = $this->exampleBuilder->forParameters(
                $this->getCallerParameters($operation),
                $surface->getTypes()
            );
            // A bulk endpoint takes an array of the single-item body.
            $payload = $this->isBodyArray($operation) ? [$body] : $body;
            $request['body'] = [
                'mode' => 'raw',
                'raw' => rtrim($this->serializer->toJson($payload)),
                'options' => ['raw' => ['language' => 'json']],
            ];
        }

        return [
            'name' => $this->getSummary($operation),
            'request' => $request,
        ];
    }

    /**
     * Build the Postman url object for an operation.
     *
     * Postman's own path-variable syntax is the colon form Magento already uses, so the route is
     * kept verbatim and the variables are declared alongside it with empty values.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<string,mixed>
     */
    private function renderUrl(OperationInterface $operation): array
    {
        $segments = array_values(
            array_filter(explode('/', $operation->getRoute()), static fn (string $s): bool => $s !== '')
        );
        array_unshift($segments, self::REST_PREFIX);

        $url = [
            'raw' => '{{' . self::VAR_BASE_URL . '}}/' . implode('/', $segments),
            'host' => ['{{' . self::VAR_BASE_URL . '}}'],
            'path' => $segments,
        ];

        $pathParameters = $this->getPathParameters($operation->getRoute());
        if ($pathParameters !== []) {
            $url['variable'] = array_map(
                static fn (string $name): array => ['key' => $name, 'value' => ''],
                $pathParameters
            );
        }

        return $url;
    }

    /**
     * Build the human-readable description shown in Postman.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return string
     */
    private function renderDescription(OperationInterface $operation): string
    {
        $parts = [
            trim($operation->getDescription()),
            '',
            '- Declared by: ' . implode(', ', $operation->getModuleNames()),
            '- Service: ' . $operation->getServiceClass() . '::' . $operation->getServiceMethod(),
            '- ACL: ' . $this->getAclSummary($operation),
            '- Kind: ' . $operation->getKind(),
        ];

        return trim(implode("\n", $parts));
    }
}
