<?php
/**
 * Copyright © Muon. All rights reserved.
 * See LICENSE.txt for license details.
 */

declare(strict_types=1);

namespace Muon\ApiSchemaExport\Model\Renderer;

use Magento\Framework\Phrase;
use Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface;
use Muon\ApiSchemaExport\Api\Data\OperationInterface;
use Muon\ApiSchemaExport\Api\Data\RenderContextInterface;
use Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer;

/**
 * Renders the surface as a Swagger 2.0 document.
 *
 * Kept alongside the OpenAPI 3.1 renderer because Magento's own /rest/all/schema endpoint serves
 * Swagger 2.0, so this output is directly comparable with what the platform itself publishes.
 * Swagger 2.0 splits the API root into scheme, host and basePath rather than a server URL, and
 * carries the request body as a parameter rather than a first-class requestBody — those two
 * differences are the whole reason this is a separate renderer instead of a post-processing step.
 */
class SwaggerRenderer extends AbstractRenderer
{
    /**
     * Renderer code.
     */
    public const CODE = 'swagger';

    /**
     * Specification version emitted.
     */
    private const SWAGGER_VERSION = '2.0';

    /**
     * Reference root for definitions.
     */
    private const REF_ROOT = '#/definitions/';

    /**
     * Magento serves its REST surface under this prefix.
     */
    private const REST_PREFIX = '/rest';

    /**
     * @param \Muon\ApiSchemaExport\Model\Renderer\SchemaBuilder $schemaBuilder
     * @param \Muon\ApiSchemaExport\Model\Serializer\DocumentSerializer $serializer
     */
    public function __construct(
        private readonly SchemaBuilder $schemaBuilder,
        private readonly DocumentSerializer $serializer
    ) {
    }

    /**
     * @inheritDoc
     */
    public function getCode(): string
    {
        return self::CODE;
    }

    /**
     * @inheritDoc
     */
    public function getLabel(): Phrase
    {
        return __('Swagger 2.0 schema');
    }

    /**
     * @inheritDoc
     */
    public function getFileExtension(RenderContextInterface $context): string
    {
        return 'swagger.' . $this->serializer->getExtension($context);
    }

    /**
     * @inheritDoc
     */
    public function getContentType(RenderContextInterface $context): string
    {
        return $this->serializer->getContentType($context);
    }

    /**
     * @inheritDoc
     */
    public function render(ApiSurfaceInterface $surface, RenderContextInterface $context): string
    {
        $paths = [];
        foreach ($surface->getOperations() as $operation) {
            $path = self::REST_PREFIX . $this->toPlaceholderPath($operation->getRoute(), '{', '}');
            $paths[$path][strtolower($operation->getHttpMethod())] = $this->renderOperation($operation);
        }
        ksort($paths);

        [$scheme, $host] = $this->splitBaseUrl($context->getBaseUrl());

        $document = [
            'swagger' => self::SWAGGER_VERSION,
            'info' => [
                'title' => $context->getTitle(),
                'version' => '1.0.0',
                'description' => 'Generated by Muon_ApiSchemaExport for: '
                    . implode(', ', $surface->getModuleNames()),
            ],
            'host' => $host,
            'schemes' => [$scheme],
            'basePath' => '/',
            'consumes' => ['application/json'],
            'produces' => ['application/json'],
            'tags' => $this->renderTags($surface),
            'paths' => $this->schemaBuilder->asMap($paths),
            'securityDefinitions' => [
                'bearerAuth' => [
                    'type' => 'apiKey',
                    'name' => 'Authorization',
                    'in' => 'header',
                    'description' => 'Bearer token. Send as: Authorization: Bearer <token>',
                ],
            ],
            'security' => [['bearerAuth' => []]],
            'definitions' => $this->schemaBuilder->asMap(
                $this->schemaBuilder->forTypes($surface->getTypes(), self::REF_ROOT)
            ),
        ];

        return $this->serializer->serialize($document, $context);
    }

    /**
     * Split a base URL into its scheme and host, as Swagger 2.0 requires them separately.
     *
     * @param string $baseUrl
     * @return array{0:string,1:string}
     */
    private function splitBaseUrl(string $baseUrl): array
    {
        $scheme = 'https';
        $host = $baseUrl;

        $separator = strpos($baseUrl, '://');
        if ($separator !== false) {
            $scheme = substr($baseUrl, 0, $separator);
            $host = substr($baseUrl, $separator + 3);
        }

        // Anything after the authority belongs to basePath, which Magento always serves from root.
        $pathStart = strpos($host, '/');
        if ($pathStart !== false) {
            $host = substr($host, 0, $pathStart);
        }

        return [$scheme, $host];
    }

    /**
     * Render the tag list, one per selected module.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\ApiSurfaceInterface $surface
     * @return array<int,array<string,string>>
     */
    private function renderTags(ApiSurfaceInterface $surface): array
    {
        $tags = [];
        foreach (array_keys($this->groupByModule($surface)) as $moduleName) {
            $tags[] = ['name' => (string)$moduleName];
        }

        return $tags;
    }

    /**
     * Render one path-item operation.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<string,mixed>
     */
    private function renderOperation(OperationInterface $operation): array
    {
        return [
            'tags' => array_values($operation->getModuleNames()),
            'operationId' => $this->getOperationId($operation),
            'summary' => $this->getSummary($operation),
            'description' => $this->renderDescription($operation),
            'parameters' => $this->renderParameters($operation),
            'responses' => $this->renderResponses($operation),
        ];
    }

    /**
     * Render path, query and body parameters into Swagger 2.0's single parameter list.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<int,array<string,mixed>>
     */
    private function renderParameters(OperationInterface $operation): array
    {
        $parameters = [];

        foreach ($this->getPathParameters($operation->getRoute()) as $name) {
            $declared = $operation->getInputParameters()[$name] ?? [];
            $schema = $this->schemaBuilder->forType(
                isset($declared['type']) ? (string)$declared['type'] : 'string',
                self::REF_ROOT
            );
            $parameters[] = [
                'name' => $name,
                'in' => 'path',
                'required' => true,
                'type' => $schema['type'] ?? 'string',
            ];
        }

        if ($operation->getHttpMethod() === 'GET') {
            foreach ($this->getCallerParameters($operation) as $name => $declared) {
                $schema = $this->schemaBuilder->forType(
                    isset($declared['type']) ? (string)$declared['type'] : 'string',
                    self::REF_ROOT
                );
                $parameters[] = [
                    'name' => (string)$name,
                    'in' => 'query',
                    'required' => (bool)($declared['required'] ?? false),
                    'type' => $schema['type'] ?? 'string',
                ];
            }

            return $parameters;
        }

        if ($this->hasBody($operation)) {
            $body = $this->schemaBuilder->forParameters(
                $this->getCallerParameters($operation),
                self::REF_ROOT
            );
            $parameters[] = [
                'name' => 'body',
                'in' => 'body',
                'required' => true,
                // A bulk endpoint takes an array of the single-item body.
                'schema' => $this->isBodyArray($operation)
                    ? ['type' => 'array', 'items' => $body]
                    : $body,
            ];
        }

        return $parameters;
    }

    /**
     * Render the response map.
     *
     * Keys are HTTP status codes. PHP coerces numeric string keys to integers, so the returned
     * array is int-keyed; JSON encoding restores them as the object keys both specifications
     * require.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return array<array-key,mixed>
     */
    private function renderResponses(OperationInterface $operation): array
    {
        $output = $operation->getOutputParameters();
        $resultType = isset($output['result']['type']) ? (string)$output['result']['type'] : null;

        $success = ['description' => 'Success.'];
        if ($resultType !== null) {
            $success['schema'] = $this->schemaBuilder->forType($resultType, self::REF_ROOT);
        }

        $responses = ['200' => $success, '400' => ['description' => 'Bad request.']];

        if ($operation->getAclResources() !== []) {
            $responses['401'] = ['description' => 'Unauthenticated.'];
            $responses['403'] = ['description' => 'Forbidden — the token lacks the required ACL resource.'];
        }
        if ($this->getPathParameters($operation->getRoute()) !== []) {
            $responses['404'] = ['description' => 'Not found.'];
        }

        return $responses;
    }

    /**
     * Build the long-form operation description.
     *
     * @param \Muon\ApiSchemaExport\Api\Data\OperationInterface $operation
     * @return string
     */
    private function renderDescription(OperationInterface $operation): string
    {
        $parts = [
            trim($operation->getDescription()),
            '',
            'Declared by: ' . implode(', ', $operation->getModuleNames()),
            'Service: ' . $operation->getServiceClass() . '::' . $operation->getServiceMethod(),
            'ACL: ' . $this->getAclSummary($operation),
            'Kind: ' . $operation->getKind(),
        ];

        return trim(implode("\n", $parts));
    }
}
